[2023-03-22T07:28:12.064+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sql_dags.load_from_mysql scheduled__2023-03-22T07:18:06.906346+00:00 [queued]>
[2023-03-22T07:28:12.074+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sql_dags.load_from_mysql scheduled__2023-03-22T07:18:06.906346+00:00 [queued]>
[2023-03-22T07:28:12.075+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:28:12.075+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-03-22T07:28:12.076+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:28:12.091+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): load_from_mysql> on 2023-03-22 07:18:06.906346+00:00
[2023-03-22T07:28:12.099+0000] {standard_task_runner.py:55} INFO - Started process 418 to run task
[2023-03-22T07:28:12.104+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sql_dags', 'load_from_mysql', 'scheduled__2023-03-22T07:18:06.906346+00:00', '--job-id', '350', '--raw', '--subdir', 'DAGS_FOLDER/sql_dags.py', '--cfg-path', '/tmp/tmpp7km2t6u']
[2023-03-22T07:28:12.105+0000] {standard_task_runner.py:83} INFO - Job 350: Subtask load_from_mysql
[2023-03-22T07:28:12.393+0000] {task_command.py:388} INFO - Running <TaskInstance: sql_dags.load_from_mysql scheduled__2023-03-22T07:18:06.906346+00:00 [running]> on host aeff5136c067
[2023-03-22T07:28:12.479+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sql_dags
AIRFLOW_CTX_TASK_ID=load_from_mysql
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T07:18:06.906346+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-22T07:18:06.906346+00:00
[2023-03-22T07:28:12.483+0000] {logging_mixin.py:137} INFO - 資料庫連接失敗： 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3306' (111)
[2023-03-22T07:28:12.483+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sql_dags.py", line 20, in load_mysql
    data = mysql_connector(query, ip, db, user, password)
  File "/opt/airflow/dags/utils/sql.py", line 37, in mysql_connector
    if (connection.is_connected()):
UnboundLocalError: local variable 'connection' referenced before assignment
[2023-03-22T07:28:12.495+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=sql_dags, task_id=load_from_mysql, execution_date=20230322T071806, start_date=20230322T072812, end_date=20230322T072812
[2023-03-22T07:28:12.509+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 350 for task load_from_mysql (local variable 'connection' referenced before assignment; 418)
[2023-03-22T07:28:12.560+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T07:28:12.814+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
