[2023-03-22T07:33:38.365+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sql_dags.load_from_mysql scheduled__2023-03-22T07:28:36.060182+00:00 [queued]>
[2023-03-22T07:33:38.377+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sql_dags.load_from_mysql scheduled__2023-03-22T07:28:36.060182+00:00 [queued]>
[2023-03-22T07:33:38.378+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:33:38.379+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-22T07:33:38.379+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:33:38.396+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): load_from_mysql> on 2023-03-22 07:28:36.060182+00:00
[2023-03-22T07:33:38.403+0000] {standard_task_runner.py:55} INFO - Started process 606 to run task
[2023-03-22T07:33:38.408+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sql_dags', 'load_from_mysql', 'scheduled__2023-03-22T07:28:36.060182+00:00', '--job-id', '366', '--raw', '--subdir', 'DAGS_FOLDER/sql_dags.py', '--cfg-path', '/tmp/tmpfys8kz2z']
[2023-03-22T07:33:38.409+0000] {standard_task_runner.py:83} INFO - Job 366: Subtask load_from_mysql
[2023-03-22T07:33:38.673+0000] {task_command.py:388} INFO - Running <TaskInstance: sql_dags.load_from_mysql scheduled__2023-03-22T07:28:36.060182+00:00 [running]> on host aeff5136c067
[2023-03-22T07:33:38.750+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sql_dags
AIRFLOW_CTX_TASK_ID=load_from_mysql
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T07:28:36.060182+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-22T07:28:36.060182+00:00
[2023-03-22T07:33:38.758+0000] {logging_mixin.py:137} INFO - 資料庫連接失敗： 2005 (HY000): Unknown MySQL server host 'docker-mysql-db-1' (-2)
[2023-03-22T07:33:38.759+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sql_dags.py", line 20, in load_mysql
    data = mysql_connector(query, ip, db, user, password)
  File "/opt/airflow/dags/utils/sql.py", line 37, in mysql_connector
    if (connection.is_connected()):
UnboundLocalError: local variable 'connection' referenced before assignment
[2023-03-22T07:33:38.770+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=sql_dags, task_id=load_from_mysql, execution_date=20230322T072836, start_date=20230322T073338, end_date=20230322T073338
[2023-03-22T07:33:38.782+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 366 for task load_from_mysql (local variable 'connection' referenced before assignment; 606)
[2023-03-22T07:33:38.822+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T07:33:38.999+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
